int ft_isalpha(char a);
int ft_isdigit(char a);
int ft_isalnum(char a);
int ft_isascii(char a);
int ft_isprint(char a);
int ft_strlen(char *a);
char ft_toupper(char a);
char ft_tolower(char a);
int ft_strncmp(char *s1, char *s2, int n);
int ft_atoi(char *str);
char *ft_strdup(char *i);
char *ft_strchr(char *a, char A);
char *ft_strrchr(char *a, char A);
int ft_strlcpy(char *dest, char *src, unsigned int N);
int ft_memcmp(const void *s1, const void *s2, size_t n);
char *ft_memcpy(const void *dest, const void *src, int n);
//int ft_memchr(char a);
//int ft_memset(char a);
//int ft_memmove(char a);
//int ft_bzero(char a);
//int ft_calloc(char a);
//int ft_strnstr(char a);